In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data/training_titanic_x_y_train.csv')
df.head()

Pclass                                            Name     Sex   Age  \
0       2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1       3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2       2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3       3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4       3                          Sutehall, Mr. Henry Jr    male  25.0   

   SibSp  Parch           Ticket    Fare Cabin Embarked  Survived  
0      1      0           228414  26.000   NaN        S         1  
1      0      0         A/5 2466   8.050   NaN        S         0  
2      0      0           250655  26.000   NaN        S         0  
3      0      4           349909  21.075   NaN        S         0  
4      0      0  SOTON/OQ 392076   7.050   NaN        S         0

In [3]:
del df['Name']

In [4]:
df.head()

Pclass     Sex   Age  SibSp  Parch           Ticket    Fare Cabin Embarked  \
0       2  female  29.0      1      0           228414  26.000   NaN        S   
1       3    male   NaN      0      0         A/5 2466   8.050   NaN        S   
2       2    male  39.0      0      0           250655  26.000   NaN        S   
3       3  female  29.0      0      4           349909  21.075   NaN        S   
4       3    male  25.0      0      0  SOTON/OQ 392076   7.050   NaN        S   

   Survived  
0         1  
1         0  
2         0  
3         0  
4         0

In [5]:
df.Cabin.value_counts(dropna=True).sum()

154

In [6]:
del df['Cabin']

In [7]:
del df['Ticket']
del df['Fare']
df.head()

Pclass     Sex   Age  SibSp  Parch Embarked  Survived
0       2  female  29.0      1      0        S         1
1       3    male   NaN      0      0        S         0
2       2    male  39.0      0      0        S         0
3       3  female  29.0      0      4        S         0
4       3    male  25.0      0      0        S         0

In [8]:
clmns_with_null = df.columns[df.isnull().any()]
df[clmns_with_null].isnull().sum()

Age         132
Embarked      1
dtype: int64

In [9]:
df.Embarked.value_counts(dropna=False)

S      484
C      133
Q       50
NaN      1
Name: Embarked, dtype: int64

In [10]:
df[df.Embarked.isnull()]

Pclass     Sex   Age  SibSp  Parch Embarked  Survived
578       1  female  38.0      0      0      NaN         1

In [11]:
df[(df['Sex'] == 'female') & (df['Age'] == 38)]

Pclass     Sex   Age  SibSp  Parch Embarked  Survived
78        1  female  38.0      1      0        C         1
578       1  female  38.0      0      0      NaN         1
603       1  female  38.0      0      0        C         1
658       3  female  38.0      1      5        S         1

In [12]:
df.at[578, 'Embarked'] = 'C'
df.Embarked.value_counts(dropna=False)

S    484
C    134
Q     50
Name: Embarked, dtype: int64

In [13]:
df.Age.describe()

count    536.000000
mean      29.700560
std       14.240257
min        0.670000
25%       21.000000
50%       29.000000
75%       38.250000
max       80.000000
Name: Age, dtype: float64

In [14]:
df.Age.median()

29.0

In [15]:
df.at[df.Age.isna(), 'Age'] = 29.0

In [16]:
clmns_with_null = df.columns[df.isnull().any()]
df[clmns_with_null].isnull().sum()

Series([], dtype: float64)

In [17]:
df.head()

Pclass     Sex   Age  SibSp  Parch Embarked  Survived
0       2  female  29.0      1      0        S         1
1       3    male  29.0      0      0        S         0
2       2    male  39.0      0      0        S         0
3       3  female  29.0      0      4        S         0
4       3    male  25.0      0      0        S         0

In [18]:
def gender(s):
    if s=='female':
        return 1
    else:
        return 0
df['Sex'] = df.Sex.apply(gender)

In [19]:
df.head()

Pclass  Sex   Age  SibSp  Parch Embarked  Survived
0       2    1  29.0      1      0        S         1
1       3    0  29.0      0      0        S         0
2       2    0  39.0      0      0        S         0
3       3    1  29.0      0      4        S         0
4       3    0  25.0      0      0        S         0

In [20]:
df.dtypes

Pclass        int64
Sex           int64
Age         float64
SibSp         int64
Parch         int64
Embarked     object
Survived      int64
dtype: object

In [21]:
def embarkd(s):
    if s=='S':
        return 0
    elif s=='C':
        return 1
    else:
        return 2
df['Embarked'] = df.Embarked.apply(embarkd)

In [22]:
df.head()

Pclass  Sex   Age  SibSp  Parch  Embarked  Survived
0       2    1  29.0      1      0         0         1
1       3    0  29.0      0      0         0         0
2       2    0  39.0      0      0         0         0
3       3    1  29.0      0      4         0         0
4       3    0  25.0      0      0         0         0

In [23]:
df.dtypes

Pclass        int64
Sex           int64
Age         float64
SibSp         int64
Parch         int64
Embarked      int64
Survived      int64
dtype: object

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(np.array(df.iloc[:, :-1]), np.array(df.iloc[:, -1]))
print(X_train.shape)
print(Y_train.shape)

(501, 6)
(501,)


In [25]:
Y_train = Y_train.reshape(-1, 1)
Y_test = Y_test.reshape(-1, 1)
Y_train.shape

(501, 1)

In [26]:
from sklearn.linear_model import LogisticRegression
algo = LogisticRegression(penalty='l2', max_iter=1000,C=0.08)

In [27]:
algo.fit(X_train, Y_train)

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=0.08, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=1000, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [28]:
algo.score(X_train, Y_train)

0.7964071856287425

In [29]:
algo.score(X_test, Y_test)

0.7784431137724551

In [30]:
x_final_test = pd.read_csv('data/test_titanic_x_test.csv')
x_final_test.head()

Pclass                                               Name     Sex   Age  \
0       2                     Davies, Master. John Morgan Jr    male   8.0   
1       1                        Leader, Dr. Alice (Farnham)  female  49.0   
2       3                            Kilgannon, Mr. Thomas J    male   NaN   
3       2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0   
4       1                          McGough, Mr. James Robert    male  36.0   

   SibSp  Parch      Ticket     Fare Cabin Embarked  
0      1      1  C.A. 33112  36.7500   NaN        S  
1      0      0       17465  25.9292   D17        S  
2      0      0       36865   7.7375   NaN        Q  
3      2      1      243847  27.0000   NaN        S  
4      0      0    PC 17473  26.2875   E25        S

In [31]:
def preprocessing(df):
    del df['Name']
    del df['Cabin']
    del df['Ticket']
    del df['Fare']
    
    def gender(s):
        if s=='female':
            return 1
        else:
            return 0
    df['Sex'] = df.Sex.apply(gender)

    def embarkd(s):
        if s=='S':
            return 0
        elif s=='C':
            return 1
        elif s=='Q':
            return 2
        else:
            return np.nan
    df['Embarked'] = df.Embarked.apply(embarkd)
    return df

In [32]:
df = preprocessing(x_final_test)
df.head()

Pclass  Sex   Age  SibSp  Parch  Embarked
0       2    0   8.0      1      1       0.0
1       1    1  49.0      0      0       0.0
2       3    0   NaN      0      0       2.0
3       2    1  24.0      2      1       0.0
4       1    0  36.0      0      0       0.0

In [33]:
df.isnull().any()

Pclass      False
Sex         False
Age          True
SibSp       False
Parch       False
Embarked     True
dtype: bool

In [34]:
null_clmns = df.columns[df.isnull().any()]
df[null_clmns].isnull().sum()

Age         45
Embarked     1
dtype: int64

In [35]:
df[df.Embarked.isnull()]

Pclass  Sex   Age  SibSp  Parch  Embarked
208       1    1  62.0      0      0       NaN

In [36]:
df[(df.Sex == 1) & (df.Age>50)]

Pclass  Sex   Age  SibSp  Parch  Embarked
10        1    1  63.0      1      0       0.0
22        1    1  58.0      0      0       0.0
35        1    1  54.0      1      0       1.0
149       1    1  56.0      0      1       1.0
192       1    1  60.0      1      0       1.0
208       1    1  62.0      0      0       NaN

In [37]:
df.at[208, ['Embarked']] = 1
df[df.Embarked.isnull()]

Empty DataFrame
Columns: [Pclass, Sex, Age, SibSp, Parch, Embarked]
Index: []

In [38]:
df.Age.describe()

count    178.000000
mean      29.694775
std       15.398053
min        0.420000
25%       19.250000
50%       27.000000
75%       37.750000
max       71.000000
Name: Age, dtype: float64

In [39]:
df.Age.median()

27.0

In [40]:
df.at[df.Age.isnull(), ['Age']] = 28.0
# df.Age.isnull()

In [41]:
df.isnull().any()

Pclass      False
Sex         False
Age         False
SibSp       False
Parch       False
Embarked    False
dtype: bool

In [42]:
df.dtypes

Pclass        int64
Sex           int64
Age         float64
SibSp         int64
Parch         int64
Embarked    float64
dtype: object

In [43]:
y_prediction = algo.predict(np.array(df))

In [44]:
y_prediction

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0], dtype=int64)

In [45]:
np.savetxt('predictions.csv',y_prediction, delimiter=',')

In [46]:
print(np.genfromtxt('predictions.csv', delimiter=','))

[0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1.
 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1.
 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0.
 1. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0. 0.
 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 1.
 0. 0. 0. 0. 1. 0. 0.]


In [48]:
from sklearn.metrics import confusion_matrix
y_train_predict = algo.predict(X_train)
y_test_predict = algo.predict(X_test)
confusion_matrix(Y_train, y_train_predict)

array([[266,  32],
       [ 70, 133]], dtype=int64)

In [49]:
confusion_matrix(Y_test, y_test_predict)

array([[91, 10],
       [27, 39]], dtype=int64)